- name: Deploy ECS task definition and service
  hosts: localhost

  vars:
      task_name: nginx
      EcsClusterName: test
      service_name: nginx_service
      container_port: 80
      container_name: nginx_con
      target_group_arn: arn:aws:elasticloadbalancing:ap-south-1:595238587347:targetgroup/nginx-taskGroup/169f549e14857e6f
      

  tasks:
    #- set_fact: EcsClusterName="test"
    - name: create task def- from ansible
      ecs_taskdefinition:
        region: ap-south-1
        containers:
        - name: "{{ container_name }}"
          cpu: 10
          essential: true
          image: "nginx"
          memory: 500
          portMappings:
          - containerPort: "{{ container_port }}"
            hostPort: 80
        launch_type: EC2
        state: present
        family: "{{ task_name }}"
      register: task_output

    - name: create ecs service
      ecs_service:
        region: ap-south-1
        state: present
        name: "{{ service_name }}"
        cluster: "{{ EcsClusterName }}"
        task_definition: "{{  task_output.taskdefinition[\"family\"]   }}"
        desired_count: 1
        load_balancers:
          - targetGroupArn: "{{ target_group_arn }}"
            containerName: "{{ container_name }}"
            containerPort: "{{ container_port }}"
      register: service_output
