- name: Deploy ECS task definition and service
  hosts: localhost

  tasks:
    - set_fact: EcsClusterName="test"
    - name: create task def- from ansible
      ecs_taskdefinition:
        #aws_access_key:
        #aws_secret_key:
        region: ap-south-1
        containers:
        - name: wordpress
          cpu: 10
          essential: true
          image: "wordpress"
          memory: 500
          links:
          - mysql
          portMappings:
          - containerPort: 80
            hostPort: 80
        - name: phpmyadmin
          cpu: 10
          essential: true
          image: "corbinu/docker-phpmyadmin"
          memory: 500
          links:
          - mysql
          environment:
          - name: "MYSQL_ROOT_PASSWORD"
            value: "password"
          - name: "MYSQL_USERNAME"
            value: "root"
          portMappings:
          - containerPort: 80
            hostPort: 8181
        - name: mysql
          cpu: 10
          essential: true
          image: "mysql"
          memory: 500
          environment:
          - name: "MYSQL_ROOT_PASSWORD"
            value: "password"
        state: present
        family: wordpress_from_ansible
        # revision: 1
      register: task_output

    - name: create ecs service
      ecs_service:
        #aws_access_key:
        #aws_secret_key:
        region: ap-south-1
        state: present
        name: wordpress_from_ansible
        cluster: "{{EcsClusterName}}"
        task_definition: "{{  task_output.taskdefinition[\"family\"]   }}:{{ task_output.taskdefinition[\"revision\"] }}"
        desired_count: 1
      register: service_output
