- name: Deploy ECS task definition and service
  hosts: localhost
  
  vars:
      task_name: chat
      EcsClusterName: test
      service_name: chat_service

  tasks:
    #- set_fact: EcsClusterName="test"
    - name: create task def- from ansible
      ecs_taskdefinition:
        region: ap-south-1
        containers:
        - name: chat
          cpu: 10
          essential: true
          image: "595238587347.dkr.ecr.ap-south-1.amazonaws.com/chatimage"
          memory: 500
          portMappings:
          - containerPort: 80
            hostPort: 80
        state: present
        family: "{{ task_name }}"
      register: task_output

    - name: create ecs service
      ecs_service:
        region: ap-south-1
        state: present
        name: "{{ service_name }}"
        cluster: "{{ EcsClusterName }}"
        task_definition: "{{  task_output.taskdefinition[\"family\"]   }}"
        desired_count: 1
      register: service_output
